# Week2事業前課題3

## 【課題1】内積を手計算しよう
以下のような行列A,Bを考えます。

行列の内積A*Bを手計算で解きなさい。

In [ ]:
A*B=[-1*0 + 2*0 + 3*2, -1*2 + 2*2 + 3*9, -1*1 + 2*-8 + 3*-1]
         [4*0 + 5*0 + 6*2, 4*2 + -5*2 +6*9, 4*1 + -5*-8 + 6*-1]
         [7*0 + 8*0 + -9*2, 7*2 + 8*2 +-9*9, 7*1 + 8*-8 + -9*-1]
       =[6, 29, -20]
         [12, 52, 38]
         [-18, -51, -48]

## 【課題2】1次元配列の内積をfor文で計算しよう
これ以降の課題はNumPyを使って解いてください。

【課題1】では手計算してもらいました。一つ一つの演算はさほど難しくありませんが、演算数は多くかなり面倒くさかったと思います。

この演算をpythonを使って実装するとどうなるのでしょうか？

手計算する際には、まず行列Aの1行目と行列Bの1列目に注目したと思います。そして、

行列Aの(0,0)の要素と行列Bの(0,0)の要素を掛け合わせる
行列Aの(0,1)の要素と行列Bの(1,0)の要素を掛け合わせる
行列Aの(0,2)の要素と行列Bの(2,0)の要素を掛け合わせる
それらの値を全て足し合わせる
というフローを得て、ようやく一つ目の要素が求まるわけです。

次の要素を計算するには、行列のindexを増やし、上の過程を再度繰り返して行けば良いわけです。下図のようなイメージですね。
Image from Gyazo

まずは、ご自身で配列のindexを指定し、

行列Aの(0,0)の要素と行列Bの(0,1)の要素を掛け合わせる
行列Aの(0,1)の要素と行列Bの(1,1)の要素を掛け合わせる
行列Aの(0,2)の要素と行列Bの(2,1)の要素を掛け合わせる
それらの値を全て足し合わせる
のフローをfor文を使って計算してください。

In [23]:
import numpy as np

A = np.array([[-1, 2, 3],
       [4, -5, 6],
       [7, 8, -9]])
B = np.array([[0, 2, 1],
       [0, 2, -8],
       [2, 9, -1]])

elem = []

for i in range(3):
    
    test = A[0,i]  * B[i,0] 
    elem.append(test)
    
sum(elem)

6

## 【課題3】多次元配列の内積をfor文で計算しよう
【課題2】ではA*Bの(0,0)だけ計算するコードを実装してもらいましたが、全要素を求めるにはどうしたら良いでしょうか？

行列A*Bの(0,1)を求めるには

行列Aのインデックスは固定（0行目を選択したまま）で、行列Bのインデックスを0列目から1列目に指定しなおせば良いわけです。理解できない方は、手計算でのフローを思い出してください！

行列Aの(0,0)の要素と行列Bの(0,1)の要素を掛け合わせる
行列Aの(0,1)の要素と行列Bの(1,1)の要素を掛け合わせる
行列Aの(0,2)の要素と行列Bの(2,1)の要素を掛け合わせる
1、2、3で求めた値を足し合わせる
とすればA*Bの(0,1)の要素が求まります。

このように同じ計算を順次インデックスを増やして行けば、全要素の計算ができます。

計算の処理自体は全て同じなので、指定する要素の場所をなんとか効率よくできないかというところで登場するのが、for文です。

説明はここまでになります。

for文を使って行列A、Bの積を計算しましょう！【課題2】では(0,0)のみ計算していただきましたが、全て計算してください。

ヒント
indexの移行は行方向と列方向があるので、【課題2】で実装していただいたコードに加えて、さらに2回for文が必要になります。


In [40]:
import numpy as np

A = np.array([[-1, 2, 3],
       [4, -5, 6],
       [7, 8, -9]])
B = np.array([[0, 2, 1],
       [0, 2, -8],
       [2, 9, -1]])

elem_all = []


for row in range(3):
    sum_elem = []
    
    for col in range(3):
        elem00 = []

        for i in range(3):

            calculation = A[row,i]  * B[i,col] 
            elem00.append(test)

        next_elem = sum(elem00)
        sum_elem.append(next_elem)

    elem_all.append(sum_elem)

elem_all

[[6, 29, -20], [12, 52, 38], [-18, -51, -48]]

In [41]:
np.array(elem_all)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

## 【課題4】内積をnp.dotで計算しよう
【課題3】ではfor文を使うことで、内積を計算していただきましたが、行列の内積演算の度にこのようにfor文の処理を何回も実装しなくてもはならないのでしょうか？

当然そんなことはなく、実はみなさんがやっていただいた処理はnumpyのメソッドですでに用意されています。

np.dot(A,B)と計算すると、【課題3】で計算していただいたことが一瞬でできます。

np.dot(A,B)を計算して、【課題3】と同じになることを試してください。


In [42]:
np.dot(A,B)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

## 【課題5】内積ができないときはどうするか
以下のような例を考えます。

行列A*Bを計算しようとすると、エラーが出て計算できません。なぜエラーが出るのか理由を記載してください。

そして、行列A、Bのどちらかにある操作をするとエラーが出ずに計算できます。

自分である操作を施し、内積を計算してください。

In [47]:
A = np.array([[-1, 2, 3],
       [4, -5, 6]])
B = np.array([[-9, 8, 7],
       [6, -5, 4]])

# アダマール積は計算できる
A*B

# 内積はエラーになる
np.dot(A,B)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

AとBの行数と列数が一致していないと積を求めることができません。
転置すれば下記の通り計算できます。

In [50]:
B = B.T
np.dot(A,B)

array([[ 46,  -4],
       [-34,  73]])